# 一. Python 数据分析概况

## Python 数据分析大家族
- numpy ： 数据结构基础
- scipy ： 强大的科学计算方法（矩阵分析、信号分析、数理分析）
- matplotlib ： 丰富的可视化套件
- pandas : 基础数据分析套件
- scikit-learn : 强大的数据分析建模库（数据挖掘、人工神经网络）
- keras : 人工神经网络 （深度人工神经网络）



# 二. Python数据分析基础技术

## numpy  http://www.numpy.org/
- 关键字： 开源 数据计算扩展
- 功能： ndarray  多维操作 线性代数


## numpy coding
1. ndarray
2. some kinds of array
3. operation
4. liner algebra
5. others...



In [8]:
import numpy as np

lst = [[1,2,3],[4,5,6]]
print(type(lst))

nplst = np.array(lst)
print(type(nplst))

nplst_float = np.array(lst, np.float)
print(type(nplst_float))

print(nplst_float.shape)
print(nplst_float.ndim)
print(nplst_float.dtype)
print(nplst_float.itemsize)
print(nplst_float.size)

<class 'list'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
(2, 3)
2
float64
8
6


### 常用数组
#### 用 numpy.random 生成各类常用数组，各类分布

In [36]:
print(np.zeros([2,13]))
print('随机数组')
print(np.random.rand(2,5))
print('随机数组-整数')
print(np.random.randint(1,10,size=(2,5)))
print('随机数组—正态分布随机数')
print(np.random.randn(2,5))
print('随机数组—从给定选择中随机选择 choice')
print(np.random.choice([2,4,7,9,12],size=(2,11)))



[[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]]
随机数组
[[ 0.35891687  0.61557461  0.90664662  0.01254681  0.83194508]
 [ 0.4326777   0.12013039  0.3585234   0.5799207   0.5071639 ]]
随机数组-整数
[[7 8 6 2 3]
 [8 8 4 2 1]]
随机数组—正态分布随机数
[[ 0.20606507  1.41097771 -2.14307405  0.77971276 -1.07259217]
 [ 0.05570864  0.27357785  0.39712092 -0.00295846 -0.34955787]]
随机数组—从给定选择中随机选择 choice
[[ 2  4  7  7  4 12  4  9  7  9  7]
 [12  7  4  2  2 12  2  2  4  7  4]]


#### 数组相关的操作

In [48]:
nplist2 = np.arange(0,100).reshape([5,20])
print(nplist2)

print(np.exp(nplist2))

print(np.sin(nplist2))


[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99]]
[[  1.00000000e+00   2.71828183e+00   7.38905610e+00   2.00855369e+01
    5.45981500e+01   1.48413159e+02   4.03428793e+02   1.09663316e+03
    2.98095799e+03   8.10308393e+03   2.20264658e+04   5.98741417e+04
    1.62754791e+05   4.42413392e+05   1.20260428e+06   3.26901737e+06
    8.88611052e+06   2.41549528e+07   6.56599691e+07   1.78482301e+08]
 [  4.85165195e+08   1.31881573e+09   3.58491285e+09   9.74480345e+09
    2.64891221e+10   7.20048993e+10   1.95729609e+11   5.32048241e+11
    1.44625706e+12   3.93133430e+12   1.06864746e+13   2.90488497e+13
    7.89629602e+13   2.14643580e+14   5.83461743e+14   1.58601345e+15
    4.31123155e+15   1.17191424e+16   3.18559318e+16 

In [52]:

print(np.sum(nplist2, axis=1))

print(np.max(nplist2, axis=1))

print('np.dot')
print(np.dot)

[ 190  590  990 1390 1790]
[19 39 59 79 99]
np.dot
<built-in function dot>


### 线性方程组 和 矩阵运算

In [54]:
from numpy.linalg import *

## 单位矩阵
print(np.eye(4))

[[ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0.  1.]]


In [63]:
lst = np.array([[1,2],
               [3,4]])

# 装置矩阵
print(lst.transpose())

#逆矩阵
print(inv(lst))


[[1 3]
 [2 4]]
[[-2.   1. ]
 [ 1.5 -0.5]]
